# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  docker: circleci/docker@1.7.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  pushing:
    docker:
      # replace with your preferred image
      - image: adebayo935/python-lettings:circleci
    steps:
      - docker/build:
          image: python-lettings
          tag: adebayo935/python-lettings:circleci
      - docker/push:
          image: adebayo935/python-lettings:circleci
workflows:
  pushing-workflow:
    jobs:
      - pushing
