# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  deploying:
    machine: true
    steps:
      - checkout
      - heroku/install
      - run:
          name: "login"
          command: "heroku login"
      - run:
          name: "push image"
          command: "python-lettings heroku container:push web"
      - run:
          name: "release image"
          command: "python-lettings heroku container:release web"
workflows:
  deploying-workflow:
    jobs:
      - deploying
