# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  deploying:
    machine: true
    steps:
      - checkout
      - run:
          name: "login"
          command: "HEROKU_API_KEY=${API_KEY} heroku container:login"
      - heroku/push-docker-image:
            app-name: python-lettings
      - heroku/release-docker-image:
            app-name: python-lettings
workflows:
  deploying-workflow:
    jobs:
      - deploying
